function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Wilbore", file = "media/maps/Wilbore/spawnpoints.lua" },
		{ name = "west_point_expansion", file = "media/maps/west_point_expansion/spawnpoints.lua" },
		{ name = "MotoriousExpandedSpawnZones", file = "media/maps/MotoriousExpandedSpawnZones/spawnpoints.lua" },
		{ name = "SaveOurStation_KnoxCountry_World", file = "media/maps/SaveOurStation_KnoxCountry_World/spawnpoints.lua" },
		{ name = "Rosewood Military Hospital", file = "media/maps/Rosewood Military Hospital/spawnpoints.lua" },
		{ name = "pz_rosewoodexp_map", file = "media/maps/pz_rosewoodexp_map/spawnpoints.lua" },
		{ name = "Riverside Fire Department", file = "media/maps/Riverside Fire Department/spawnpoints.lua" },
		{ name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua" },
		{ name = "Many Spawns Casual", file = "media/maps/Many Spawns Casual/spawnpoints.lua" },
		{ name = "Many Spawns root", file = "media/maps/Many Spawns root/spawnpoints.lua" },
		{ name = "Many Spawns All", file = "media/maps/Many Spawns All/spawnpoints.lua" },
		{ name = "Dixie", file = "media/maps/Dixie/spawnpoints.lua" },
		{ name = "Ekron", file = "media/maps/Ekron/spawnpoints.lua" },
		{ name = "Industrial Zone", file = "media/maps/Industrial Zone/spawnpoints.lua" },
		{ name = "March Ridge", file = "media/maps/March Ridge/spawnpoints.lua" },
		{ name = "McCoy Logging", file = "media/maps/McCoy Logging/spawnpoints.lua" },
		{ name = "Muldraugh", file = "media/maps/Muldraugh/spawnpoints.lua" },
		{ name = "Riveside", file = "media/maps/Riveside/spawnpoints.lua" },
		{ name = "West Point", file = "media/maps/West Point/spawnpoints.lua" },
		{ name = "By Profession", file = "media/maps/By Profession/spawnpoints.lua" },
		{ name = "Many Spawns All Reduced", file = "media/maps/Many Spawns All Reduced/spawnpoints.lua" },
		{ name = "Many Spawns Knox Reduced", file = "media/maps/Many Spawns Knox Reduced/spawnpoints.lua" },
		{ name = "Knox County Building Inspector", file = "media/maps/Knox County Building Inspector/spawnpoints.lua" },
		{ name = "Knox County Car Wrecks", file = "media/maps/Knox County Car Wrecks/spawnpoints.lua" },
		{ name = "Knox County Hitchhikers", file = "media/maps/Knox County Hitchhikers/spawnpoints.lua" },
		{ name = "Knox County Patients", file = "media/maps/Knox County Patients/spawnpoints.lua" },
		{ name = "Knox County Prisoners", file = "media/maps/Knox County Prisoners/spawnpoints.lua" },
		{ name = "Knox County Schools", file = "media/maps/Knox County Schools/spawnpoints.lua" },
		{ name = "Knox County Visitors", file = "media/maps/Knox County Visitors/spawnpoints.lua" },
		{ name = "Muldraugh Fire Department", file = "media/maps/Muldraugh Fire Department/spawnpoints.lua" },
		{ name = "Westoutskirts-shippingCo", file = "media/maps/Westoutskirts-shippingCo/spawnpoints.lua" },
		{ name = "Dixie, KY", file = "media/maps/Dixie, KY/spawnpoints.lua" },
		{ name = "Ekron, KY", file = "media/maps/Ekron, KY/spawnpoints.lua" },
		{ name = "March Ridge, KY", file = "media/maps/March Ridge, KY/spawnpoints.lua" },
		{ name = "Valley Station, KY", file = "media/maps/Valley Station, KY/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Fort Benning", file = "media/maps/Fort Benning/spawnpoints.lua" },
		{ name = "ForagingZ", file = "media/maps/ForagingZ/spawnpoints.lua" },
		{ name = "Anthem, KY", file = "media/maps/Anthem, KY/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
	}
end
